const CATEGORIES = [
  { id: 'key', label: 'Key Items' },
  { id: 'major', label: 'Major Bosses' },
  { id: 'boss', label: 'Other Bosses' },
  { id: 'flask', label: 'Flask Upgrades' },
  { id: 'shop', label: 'Shops' },
  { id: 'blessing', label: 'Blessing Pickups' },
];

const DATA = [
  { section: null, locations: [
    { name: "Limgrave", items: [
      { desc: "In a chest at the top of a tower in Fort Haight", replaces: "Dectus Medallion (Left)", cat: "key" },
      { desc: "Dropped by Bloodhound Knight Darriwil in Forlorn Hound Evergaol", replaces: "Bloodhound's Fang", cat: "boss" },
      { desc: "Dropped by Flying Dragon Agheel", replaces: "Dragon Heart", cat: "boss" },
      { desc: "Dropped by the Night's Cavalry on the bridge eastward of Agheel Lake North. They only spawn at night", replaces: "Ash of War: Repeating Thrust", cat: "boss" },
      { desc: "Dropped by the Tibia Mariner in Summonwater Village", replaces: "Deathroot, Skeletal Militiaman Ashes", cat: "boss" },
      { desc: "Dropped by the Tree Sentinel before the Church of Elleh", replaces: "Golden Halberd", cat: "boss" },
      { desc: "At the statue in the Third Church of Marika, northeast of the Mistwood", replaces: "Sacred Tear", cat: "flask" },
      { desc: "Under a Golden Seed tree in front of Fort Haight", replaces: "Golden Seed", cat: "flask" },
      { desc: "Sold by Kale at the Church of Elleh", replaces: null, cat: "shop" },
      { desc: "Sold by the Nomadic Merchant between Saintsbridge and Summonwater Village", replaces: null, cat: "shop" },
      { desc: "Sold by the Nomadic Merchant in front of Coastal Cave", replaces: null, cat: "shop" },
      { desc: "Sold by the Nomadic Merchant in the Mistwood along the road to Fort Haight", replaces: null, cat: "shop" },
      { desc: "Fringefolk Hero's Grave - Dropped by Ulcerated Tree Spirit", replaces: "Golden Seed, Banished Knight Oleg", cat: "boss" },
      { desc: "Coastal Cave - Dropped by Demi-Human Chiefs", replaces: "Tailoring Tools, Sewing Needle", cat: "boss" },
      { desc: "Stormfoot Catacombs Dropped by Erdtree Burial Watchdog", replaces: "Noble Sorcerer Ashes", cat: "boss" },
      { desc: "Murkwater Catacombs - Dropped by Grave Warden Duelist", replaces: "Banished Knight Engvall", cat: "boss" },
      { desc: "Groveside Cave - Dropped by Beastman of Farum Azula", replaces: "Flamedrake Talisman", cat: "boss" },
      { desc: "Highroad Cave - Dropped by Guardian Golem", replaces: "Blue Dancer Charm", cat: "boss" },
      { desc: "Limgrave Tunnels - Dropped by Stonedigger Troll", replaces: "Roar Medallion", cat: "boss" },
      { desc: "Murkwater Cave - Sold by Patches", replaces: null, cat: "shop" },
    ]},
    { name: "Stormhill", items: [
      { desc: "Dropped by Margit the Fell Omen or Morgott the Omen King", replaces: "Talisman Pouch", cat: "major" },
      { desc: "Dropped by a Deathbird to the east of Warmaster's Shack. They only spawn at night", replaces: "Blue-Feathered Branchsword", cat: "boss" },
      { desc: "Dropped by the Bell Bearing Hunter who invades at Warmaster's Shack at night", replaces: "Bone Peddler's Bell Bearing", cat: "boss" },
      { desc: "Dropped by the Crucible Knight in the Stormhill Evergaol", replaces: "Aspects of the Crucible: Tail", cat: "boss" },
      { desc: "Under a Golden Seed tree along the road from Gatefront to Stormhill Shack", replaces: "Golden Seed", cat: "flask" },
      { desc: "Deathtouched Catacombs - Dropped by Black Knife Assassin", replaces: "Assassin's Crimson Dagger", cat: "boss" },
    ]},
    { name: "Stormveil Castle", items: [
      { desc: "In the dark room before the Rusty Key door, guarded by a Banished Knight", replaces: "Rusty Key", cat: "key" },
      { desc: "Dropped by Godrick the Grafted", replaces: "Godrick's Great Rune, Remembrance of the Grafted", cat: "major" },
      { desc: "Under a Golden Seed tree on the way to Godrick the Grafted", replaces: "Golden Seed", cat: "flask" },
    ]},
    { name: "Weeping Peninsula", items: [
      { desc: "Dropped by Leonine Misbegotten south of Castle Morne", replaces: "Grafted Blade Greatsword", cat: "major" },
      { desc: "Dropped by Ancient Hero of Zamor in the Weeping Evergaol, northwest of the Fourth Church of Marika near the west coast", replaces: "Radagon's Scarseal", cat: "boss" },
      { desc: "Dropped by the Deathbird up the hill directly north of Castle Morne. They only spawn at night", replaces: "Sacrificial Axe", cat: "boss" },
      { desc: "Dropped by the Erdtree Avatar at the Weeping Peninsula Minor Erdtree", replaces: "Opaline Bubbletear, Crimsonburst Crystal Tear", cat: "boss" },
      { desc: "Dropped by the Night's Cavalry at Castle Morne Rampart. They only spawn at night", replaces: "Nightrider Flail, Ash of War: Barricade Shield", cat: "boss" },
      { desc: "At the interesting statue in the Church of Pilgrimage on the Weeping Peninsula north coast", replaces: "Sacred Tear", cat: "flask" },
      { desc: "At the statue in Callu Baptismal Church, south of Ailing Village", replaces: "Sacred Tear", cat: "flask" },
      { desc: "At the statue in the Fourth Church of Marika, near the peninsula's west coast", replaces: "Sacred Tear", cat: "flask" },
      { desc: "Under the Golden Seed tree straight north of Castle Morne, leaning right when approaching from Castle Morne Rampart", replaces: "Golden Seed", cat: "flask" },
      { desc: "Sold by the Isolated Merchant at the Isolated Merchant Shack near the southwest shore", replaces: null, cat: "shop" },
      { desc: "Sold by the Nomadic Merchant at Castle Morne Rampart", replaces: null, cat: "shop" },
      { desc: "Tombsward Catacombs - Dropped by Cemetery Shade", replaces: "Lhutel the Headless", cat: "boss" },
      { desc: "Impaler's Catacombs - Dropped by Erdtree Burial Watchdog", replaces: "Demi-Human Ashes", cat: "boss" },
      { desc: "Earthbore Cave - Dropped by Runebear", replaces: "Spelldrake Talisman", cat: "boss" },
      { desc: "Tombsward Cave - Dropped by Miranda the Blighted Bloom", replaces: "Viridian Amber Medallion", cat: "boss" },
      { desc: "Morne Tunnel - Dropped by Scaly Misbegotten", replaces: "Rusted Anchor", cat: "boss" },
    ]},
    { name: "Liurnia", items: [
      { desc: "Given by Albus the Albinauric in Village of the Albinauric if you roll into him (he is disguised as a pot)", replaces: "Haligtree Secret Medallion (Right)", cat: "key" },
      { desc: "Guarded by Glintstone Dragon Smarag", replaces: "Academy Glintstone Key", cat: "key" },
      { desc: "In a chest at the topmost of the Belfries", replaces: "Imbued Sword Key", cat: "key" },
      { desc: "Dropped by Royal Knight Loretta", replaces: "Loretta's Greatbow, Ash of War: Loretta's Slash", cat: "major" },
      { desc: "Dropped by Adan, Thief of Fire in the Malefactor's Evergaol", replaces: "Flame of the Fell God", cat: "boss" },
      { desc: "Dropped by Bols, Carian Knight in Cuckoo's Evergaol", replaces: "Greatblade Phalanx", cat: "boss" },
      { desc: "Dropped by Erdtree Avatar at the Minor Erdtree north of Converted Tower in West Liurnia", replaces: "Cerulean Crystal Tear, Ruptured Crystal Tear", cat: "boss" },
      { desc: "Dropped by Glintstone Dragon Smarag", replaces: "Dragon Heart", cat: "boss" },
      { desc: "Dropped by Omenkiller in Village of the Albinaurics, across the stone bridge from the Site of Grace", replaces: "Crucible Knot Talisman", cat: "boss" },
      { desc: "Dropped by the Bell Bearing Hunter who invades at Church of Vows at night", replaces: "Meat Peddler's Bell Bearing", cat: "boss" },
      { desc: "Dropped by the Death Rite Bird south of Gate Town North. They only spawn at night", replaces: "Ancient Death Rancor", cat: "boss" },
      { desc: "Dropped by the Deathbird north of the Scenic Isle Site of Grace. They only spawn at night", replaces: "Red-Feathered Branchsword", cat: "boss" },
      { desc: "Dropped by the Night's Cavalry east of the Gate Town Bridge Site of Grace. They only spawn at night", replaces: "Ash of War: Ice Spear", cat: "boss" },
      { desc: "Dropped by the Tibia Mariner down the hill from Artist's Shack, to the south", replaces: "Deathroot, Skeletal Bandit Ashes", cat: "boss" },
      { desc: "At the statue in Church of Irith, south of Lake-Facing Cliffs Site of Grace", replaces: "Sacred Tear", cat: "flask" },
      { desc: "Under a Golden Seed tree after Manor Upper Level in Caria Manor", replaces: "Golden Seed", cat: "flask" },
      { desc: "Under a Golden Seed tree near the Ravine-Veiled Village before Ruin-Strewn Precipice", replaces: "Golden Seed", cat: "flask" },
      { desc: "Under a Golden Seed tree to the west of the bottom of the heavily guarded stairway up to South Raya Lucaria Gate", replaces: "Golden Seed", cat: "flask" },
      { desc: "Sold by Iji", replaces: null, cat: "shop" },
      { desc: "Sold by the Nomadic Merchant by the Liurnia Lake Shore Site of Grace", replaces: null, cat: "shop" },
      { desc: "Behind Caria Manor - Dropped by the Onyx Lord in the Royal Grave Evergaol", replaces: "Meteorite", cat: "boss" },
      { desc: "Behind Caria Manor - Sold by Pidia. He can be found by dropping back down into Caria Manor off a cliffside from the Three Sisters", replaces: null, cat: "shop" },
      { desc: "Road's End Catacombs - Dropped by Spiritcaller Snail", replaces: "Glintstone Sorcerer Ashes", cat: "boss" },
      { desc: "Black Knife Catacombs - Dropped by Black Knife Assassin", replaces: "Assassin's Cerulean Dagger, Black Knifeprint", cat: "boss" },
      { desc: "Black Knife Catacombs - Dropped by Cemetery Shade", replaces: "Twinsage Sorcerer Ashes", cat: "boss" },
      { desc: "Cliffbottom Catacombs - Dropped by Erdtree Burial Watchdog", replaces: "Kaiden Sellsword Ashes", cat: "boss" },
      { desc: "Stillwater Cave - Dropped by Cleanrot Knight", replaces: "Winged Sword Insignia", cat: "boss" },
      { desc: "Lakeside Crystal Cave - Dropped by Bloodhound Knight", replaces: "Cerulean Amber Medallion", cat: "boss" },
      { desc: "Academy Crystal Cave - Dropped by Crystalians", replaces: "Crystal Release", cat: "boss" },
      { desc: "Raya Lucaria Crystal Tunnel - Dropped by Crystalian", replaces: "Smithing-Stone Miner's Bell Bearing [1]", cat: "boss" },
    ]},
    { name: "Bellum Highway", items: [
      { desc: "Dropped by Erdtree Avatar at the Minor Erdtree south of Frenzied Flame Village in East Liurnia", replaces: "Magic-Shrouding Cracked Tear, Lightning-Shrouding Cracked Tear, Holy-Shrouding Cracked Tear", cat: "boss" },
      { desc: "Dropped by the Night's Cavalry between East Raya Lucaria Gate and Bellum Church. They only spawn at night", replaces: "Nightrider Glaive, Ash of War: Giant Hunt", cat: "boss" },
      { desc: "At the interesting statue in Bellum Church", replaces: "Sacred Tear", cat: "flask" },
      { desc: "At the statue in Church of Inhibition", replaces: "Sacred Tear", cat: "flask" },
      { desc: "Sold by Nomadic Merchant down the cliffside pathway from Bellum Church", replaces: null, cat: "shop" },
    ]},
    { name: "Academy of Raya Lucaria", items: [
      { desc: "On a robed corpse in the Raya Lucaria rooftop path, accessed by looping around from Debate Parlor by dropping down past the rubble-strewn stairs", replaces: "Imbued Sword Key", cat: "key" },
      { desc: "In a chest unlocked by Discarded Palace Key in the Raya Lucaria Grand Library", replaces: "Dark Moon Ring", cat: "key" },
      { desc: "Dropped by Red Wolf of Radagon", replaces: "Memory Stone", cat: "major" },
      { desc: "Dropped by Rennala", replaces: "Great Rune of the Unborn, Remembrance of the Full Moon Queen", cat: "major" },
      { desc: "Under a Golden Seed tree on a bridge to north of the Main Academy Gate", replaces: "Golden Seed", cat: "flask" },
      { desc: "Under a Golden Seed tree in the courtyard after Debate Parlor, along a cliffside in the back right", replaces: "Golden Seed", cat: "flask" },
      { desc: "Sold by Isolated Merchant southeast of Main Academy Gate", replaces: null, cat: "shop" },
    ]},
    { name: "Divine Tower of Liurnia", items: [
      { desc: "At the top of the Divine Tower of Liurnia, accessed after traversing Carian Study Hall", replaces: "Stargazer Heirloom, Cursemark of Death", cat: "key" },
    ]},
    { name: "Siofra River", items: [
      { desc: "Dropped by Ancestor Spirit", replaces: "Ancestral Follower Ashes", cat: "major" },
      { desc: "Dropped by Dragonkin Soldier. They can be reached either from Nokron or from a sending gate in Siofra River", replaces: "Dragon Halberd", cat: "boss" },
      { desc: "Under a Golden Seed tree across a narrow stone bridge, shortly before the elevator up to Caelid at the end of Siofra River", replaces: "Golden Seed", cat: "flask" },
      { desc: "Sold by the Abandoned Merchant overlooking the Giant Miranda Flower. He can be found by ascending up wooden scaffolding near Worshippers' Woods and dropping down towards a short tunnel", replaces: null, cat: "shop" },
    ]},
    { name: "Nokron, Eternal City", items: [
      { desc: "Dropped by Mimic Tear", replaces: "Silver Tear Mask, Larval Tear 2x", cat: "major" },
      { desc: "Dropped by Regal Ancestor Spirit", replaces: "Remembrance of the Regal Ancestor", cat: "major" },
      { desc: "Dropped by Valiant Gargoyles after Siofra Aqueduct", replaces: "Gargoyle's Greatsword, Gargoyle's Twinblade", cat: "major" },
    ]},
    { name: "Ainsel River", items: [
      { desc: "Dropped by Astel, Naturalborn of the Void", replaces: "Remembrance of the Naturalborn", cat: "major" },
      { desc: "Under a Golden Seed tree on a cliffside overlooking the elevator down to Nokstella Waterfall Basin", replaces: "Golden Seed", cat: "flask" },
    ]},
    { name: "Ainsel River Downstream", items: [
      { desc: "Dropped by Dragonkin Soldier of Nokstella", replaces: "Frozen Lightning Spear", cat: "major" },
      { desc: "Sold by the Hermit Merchant in the alcove past the rock-slinging Malformed Star", replaces: null, cat: "shop" },
    ]},
    { name: "Deeproot Depths", items: [
      { desc: "Dropped by Crucible Knight Siluria", replaces: "Siluria's Tree", cat: "boss" },
      { desc: "Dropped by Fia's Champion", replaces: "Fia's Mist", cat: "boss" },
    ]},
    { name: "Ruin-Strewn Precipice", items: [
      { desc: "Dropped by Magma Wyrm Makar", replaces: "Magma Wyrm's Scalesword, Dragon Heart", cat: "major" },
    ]},
    { name: "Caelid", items: [
      { desc: "In a chest hidden behind a magical barrier in Sellia, accessed by lighting flames around town", replaces: "Imbued Sword Key", cat: "key" },
      { desc: "Dropped by Starscourge Radahn", replaces: "Radahn's Great Rune, Remembrance of the Starscourge", cat: "major" },
      { desc: "Dropped by Commander O'Neil in the Heart of Aeonia", replaces: "Commander's Standard, Unalloyed Gold Needle (Broken)", cat: "boss" },
      { desc: "Dropped by Decaying Ekzykes, south of the Caelid Highway South Site of Grace", replaces: "Dragon Heart", cat: "boss" },
      { desc: "Dropped by Nox Swordstress and Nox Priest in the Sellia Chair-Crypt, accessed by lighting flames around town and continuing north", replaces: "Nox Flowing Sword", cat: "boss" },
      { desc: "Dropped by Putrid Avatar down the hill northeast of Smoldering Church", replaces: "Greenburst Crystal Tear, Flame-Shrouding Cracked Tear", cat: "boss" },
      { desc: "Dropped by the Death Rite Bird southeast of Southern Aeonia Swamp Bank Site of Grace. They only spawn at night", replaces: "Death's Poker", cat: "boss" },
      { desc: "Dropped by the Night's Cavalry west of Southern Aeonia Swamp Bank Site of Grace. They only spawn at night", replaces: "Ash of War: Poison Moth Flight", cat: "boss" },
      { desc: "Dropped by the Crucible Knight and Misbegotten Warrior at Redmane Castle. They can be accessed either before triggering the Radahn Festival or after defeating him and talking to Jerren", replaces: "Ruins Greatsword", cat: "boss" },
      { desc: "At the statue in Church of the Plague", replaces: "Sacred Tear", cat: "flask" },
      { desc: "Under a Golden Seed tree on the road from Southern Aeonia Swamp Bank to Impassable Greatbridge", replaces: "Golden Seed", cat: "flask" },
      { desc: "Under a Golden Seed tree up the stairs at the north end of Sellia", replaces: "Golden Seed", cat: "flask" },
      { desc: "Sold by the Nomadic Merchant between Astray from Caelid Highway North and Aeonia Swamp Shore", replaces: null, cat: "shop" },
      { desc: "Sold by the Nomadic Merchant southwest of southern Aeonia Swamp Bank", replaces: null, cat: "shop" },
      { desc: "Minor Erdtree Catacombs - Dropped by Erdtree Burial Watchdog", replaces: "Mad Pumpkin Head Ashes", cat: "boss" },
      { desc: "Caelid Catacombs - Dropped by Cemetery Shade", replaces: "Kindred of Rot Ashes", cat: "boss" },
      { desc: "War-Dead Catacombs - Dropped by Putrid Tree Spirit", replaces: "Golden Seed, Redmane Knight Ogha", cat: "boss" },
      { desc: "Abandoned Cave - Dropped by Cleanrot Knights", replaces: "Gold Scarab", cat: "boss" },
      { desc: "Gaol Cave - Dropped by Grave Warden Duelist", replaces: "Putrid Corpse Ashes", cat: "boss" },
      { desc: "Gael Tunnel - Dropped by Magma Wyrm", replaces: "Moonveil, Dragon Heart", cat: "boss" },
      { desc: "Sellia Crystal Tunnel - Dropped by Fallingstar Beast", replaces: "Gravity Stone Chunk 10x, Somberstone Miner's Bell Bearing [1], Smithing Stone [7] 5x, Somber Smithing Stone [6]", cat: "boss" },
    ]},
    { name: "Dragonbarrow", items: [
      { desc: "In a chest up the first ladder at Fort Faroth", replaces: "Dectus Medallion (Right)", cat: "key" },
      { desc: "Dropped by Battlemage Hugues in the Sellia Evergaol, atop a cliff overlooking Sellia, accessible from the Dragonbarrow West Site of Grace", replaces: "Battlemage Hugues", cat: "boss" },
      { desc: "Dropped by Black Blade Kindred in front of Bestial Sanctum", replaces: "Gargoyle's Blackblade, Gargoyle's Black Halberd", cat: "boss" },
      { desc: "Dropped by Flying Dragon Greyll on Farum Greatbridge", replaces: "Dragon Heart", cat: "boss" },
      { desc: "Dropped by the Bell Bearing Hunter who invades at Isolated Merchant's Shack at night", replaces: "Gravity Stone Peddler's Bell Bearing", cat: "boss" },
      { desc: "Dropped by the Night's Cavalry on the smaller bridge to the east of Farum Greatbridge. They only spawn at night", replaces: "Ash of War: Bloodhound's Step", cat: "boss" },
      { desc: "Dropped by the Putrid Avatar at the Dragonbarrow Minor Erdtree", replaces: "Opaline Hardtear, Stonebarb Cracked Tear", cat: "boss" },
      { desc: "Under a Golden Seed tree on the road from Farum Greatbridge from Bestial Sanctum", replaces: "Golden Seed", cat: "flask" },
      { desc: "Sold by the Isolated Merchant at Isolated Merchant's Shack", replaces: null, cat: "shop" },
      { desc: "Dragonbarrow Cave - Dropped by Beastman of Farum Azula", replaces: "Flamedrake Talisman +2", cat: "boss" },
      { desc: "Sellia Hideaway - Dropped by Putrid Crystalians", replaces: "Crystal Torrent", cat: "boss" },
    ]},
    { name: "Divine Tower of Caelid", items: [
      { desc: "Dropped by Godskin Apostle", replaces: "Godskin Apostle Hood, Godskin Apostle Robe, Godskin Apostle Bracelets, Godskin Apostle Trousers", cat: "boss" },
    ]},
    { name: "Altus Plateau", items: [
      { desc: "Dropped by Elemer of the Briar", replaces: "Marais Executioner's Sword, Briar Greatshield", cat: "major" },
      { desc: "Dropped by Ancient Dragon Lansseax up the hill from Abandoned Coffin", replaces: "Lansseax's Glaive", cat: "boss" },
      { desc: "Dropped by Fallingstar Beast to the south of Tree Sentinel Duo, veering right on the path from Altus Highway Junction to Outer Wall Phantom Tree", replaces: "Gravity Stone Fan 10x, Gravity Stone Chunk 10x, Smithing Stone [6] 5x, Somber Smithing Stone [5]", cat: "boss" },
      { desc: "Dropped by Godefroy the Grafted in the Golden Lineage Evergaol", replaces: "Godfrey Icon", cat: "boss" },
      { desc: "Dropped by Godskin Apostle at the elevated north cliffside of Windmill Village", replaces: "Godskin Peeler, Scouring Black Flame", cat: "boss" },
      { desc: "Dropped by the Black Knight Assassin camping out in front of Sainted Hero's Grave", replaces: "Black Knife", cat: "boss" },
      { desc: "Dropped by the Deathbird straight east of the Hermit Merchant's Shack. They only spawn at night", replaces: "Twinbird Kite Shield", cat: "boss" },
      { desc: "Dropped by the Night's Cavalry on the road from the Grand Lift of Dectus to Altus Highway Junction. They only spawn at night", replaces: "Ash of War: Shared Order", cat: "boss" },
      { desc: "Dropped by the Tibia Mariner in Wyndham Ruins", replaces: "Deathroot, Tibia's Summons", cat: "boss" },
      { desc: "Dropped by Tree Sentinel Duo, at the top of the stairs from Altus Highway Junction to Outer Wall Phantom Tree", replaces: "Erdtree Greatshield, Hero's Rune [1]", cat: "boss" },
      { desc: "Dropped by Wormface at the Altus Plateau Minor Erdtree", replaces: "Crimsonspill Crystal Tear, Speckled Hardtear", cat: "boss" },
      { desc: "At the interesting statue in Stormcaller Church, south of Sainted Hero's Grave", replaces: "Sacred Tear", cat: "flask" },
      { desc: "At the statue in the Second Church of Marika (blood dog haunts)", replaces: "Sacred Tear", cat: "flask" },
      { desc: "Under a Golden Seed tree down the southeast road from Windmill Village", replaces: "Golden Seed", cat: "flask" },
      { desc: "Under a Golden Seed tree found up the stairs from Outer Wall Phantom Tree", replaces: "Golden Seed, Golden Seed", cat: "flask" },
      { desc: "Under a Golden Seed tree next to the Erdtree-Gazing Hill Site of Grace", replaces: "Golden Seed", cat: "flask" },
      { desc: "Under a Golden Seed tree, found north of the Altus Highway Junction Site of Grace", replaces: "Golden Seed", cat: "flask" },
      { desc: "Under a Golden Seed tree, found north of the Altus Plateau Minor Erdtree", replaces: "Golden Seed", cat: "flask" },
      { desc: "Sold by the Nomadic Merchant at the southern end of the Forest-Spanning Greatbridge", replaces: null, cat: "shop" },
      { desc: "Sainted Hero's Grave - Dropped by Ancient Hero of Zamor", replaces: "Ancient Dragon Knight Kristoff", cat: "boss" },
      { desc: "Unsightly Catacombs - Dropped by Perfumer Tricia and Misbegotten Warrior", replaces: "Perfumer Tricia", cat: "boss" },
      { desc: "Perfumer's Grotto - Dropped by Omenkiller and Giant Miranda Flower", replaces: "Great Omenkiller Cleaver", cat: "boss" },
      { desc: "Sage's Cave - Dropped by Black Knife Assassin", replaces: "Concealing Veil", cat: "boss" },
      { desc: "Sage's Cave - Dropped by Necromancer Garris", replaces: "Family Heads", cat: "boss" },
      { desc: "Old Altus Tunnel - Dropped by Stonedigger Troll", replaces: "Great Club", cat: "boss" },
      { desc: "Altus Tunnel - Dropped by Crystalians", replaces: "Somberstone Miner's Bell Bearing [2]", cat: "boss" },
    ]},
    { name: "Capital Outskirts", items: [
      { desc: "Dropped by the Bell Bearing Hunter who invades at Hermit Merchant's Shack at night", replaces: "Medicine Peddler's Bell Bearing", cat: "boss" },
      { desc: "Under the Golden Seed tree at Outer Wall Phantom Tree", replaces: "Golden Seed, Golden Seed", cat: "flask" },
      { desc: "Sold by the Hermit Merchant at the Hermit's Merchant Shack", replaces: null, cat: "shop" },
      { desc: "Sealed Tunnel - Dropped by Onyx Lord", replaces: "Onyx Lord's Greatsword", cat: "boss" },
      { desc: "Auriza Hero's Grave - Dropped by Crucible Knight Duo", replaces: "Ordovis's Greatsword, Crucible Axe Helm, Crucible Axe Armor, Crucible Gauntlets, Crucible Greaves", cat: "boss" },
      { desc: "Auriza Side Tomb - Dropped by Grave Warden Duelist", replaces: "Soldjars of Fortune Ashes", cat: "boss" },
    ]},
    { name: "Divine Tower of East Altus", items: [
      { desc: "Dropped by Fell Twins", replaces: "Omenkiller Rollo", cat: "boss" },
    ]},
    { name: "Leyndell", items: [
      { desc: "Given by Melina after defeating Morgott", replaces: "Rold Medallion", cat: "key" },
      { desc: "Dropped by Godfrey, First Elden Lord, in the Erdtree Sanctuary", replaces: "Talisman Pouch", cat: "major" },
      { desc: "Dropped by Morgott the Omen King", replaces: "Morgott's Great Rune, Remembrance of the Omen King", cat: "major" },
      { desc: "Under the Golden Seed tree down the hall from West Capital Rampart, up the giant dragon's wing", replaces: "Golden Seed", cat: "flask" },
      { desc: "Leyndell Catacombs - Dropped by Esgar, Priest of Blood", replaces: "Lord of Blood's Exultation", cat: "boss" },
    ]},
    { name: "Subterranean Shunning-Grounds", items: [
      { desc: "Dropped by Mohg the Omen", replaces: "Bloodflame Talons", cat: "major" },
    ]},
    { name: "Roundtable Hold", items: [
      { desc: "Sold by Twin Maiden Husks", replaces: null, cat: "shop" },
    ]},
    { name: "Mt. Gelmir", items: [
      { desc: "Dropped by Demi-Human Queen Maggie in Hermit Village", replaces: "Memory Stone", cat: "boss" },
      { desc: "Dropped by Full-Grown Fallingstar Beast after Ninth Mt. Gelmir Campsite", replaces: "Fallingstar Beast Jaw, Smithing Stone [6] 5x, Somber Smithing Stone [6]", cat: "boss" },
      { desc: "Dropped by the Magma Wyrm behind Fort Laiedd", replaces: "Dragon Heart", cat: "boss" },
      { desc: "Dropped by the Ulcerated Tree Spirit at the Mt. Gelmir Minor Erdtree", replaces: "Leaden Hardtear, Cerulean Hidden Tear", cat: "boss" },
      { desc: "Under a Golden Seed tree before the Road of Iniquity Site of Grace", replaces: "Golden Seed", cat: "flask" },
      { desc: "Under a Golden Tree found following Seethwater River north", replaces: "Golden Seed", cat: "flask" },
      { desc: "Sold by the Nomadic Merchant in the long ladder section before Ninth Mt. Gelmir Campsite", replaces: null, cat: "shop" },
      { desc: "Wyndham Catacombs - Dropped by Erdtree Burial Watchdog", replaces: "Glovewort Picker's Bell Bearing [1]", cat: "boss" },
      { desc: "Gelmir Hero's Grave - Dropped by Red Wolf of the Champion", replaces: "Bloodhound Knight Floh", cat: "boss" },
      { desc: "Seethewater Cave - Dropped by Kindred of Rot", replaces: "Kindred of Rot's Exultation", cat: "boss" },
      { desc: "Volcano Cave - Dropped by Demi-Human Queen Margot", replaces: "Jar Cannon", cat: "boss" },
    ]},
    { name: "Volcano Manor", items: [
      { desc: "Given by Tanith upon joining Volcano Manor, or in her chair after defeating Rykard", replaces: "Drawing-Room Key", cat: "key" },
      { desc: "Dropped by Godskin Noble", replaces: "Godskin Stitcher, Noble Presence", cat: "major" },
      { desc: "Dropped by Rykard", replaces: "Rykard's Great Rune, Remembrance of the Blasphemous", cat: "major" },
      { desc: "Dropped by Abductor Virgins", replaces: "Inquisitor's Girandole", cat: "boss" },
    ]},
    { name: "Lake of Rot", items: [
      { desc: "Dropped by Dragonkin Soldier", replaces: "Dragonscale Blade", cat: "boss" },
    ]},
    { name: "Moonlight Altar", items: [
      { desc: "Dropped by Alecto, Black Knife Ringleader in Ringleader's Evergaol", replaces: "Black Knife Tiche", cat: "boss" },
      { desc: "Dropped by Glintstone Dragon Adula", replaces: "Adula's Moonblade, Dragon Heart 3x", cat: "boss" },
    ]},
    { name: "Forbidden Lands", items: [
      { desc: "Dropped by Black Blade Kindred before the Grand Lift of Rold", replaces: "Gargoyle's Black Blades, Gargoyle's Black Axe", cat: "boss" },
      { desc: "Dropped by the Night's Cavalry on the path from Forbidden Lands to the Grand Lift of Rold. They only spawn at night", replaces: "Ash of War: Phantom Slash", cat: "boss" },
      { desc: "Under a Golden Seed tree in Forbidden Lands before the stairs to the Grand Lift of Rold", replaces: "Golden Seed", cat: "flask" },
    ]},
    { name: "Mountaintops of the Giants", items: [
      { desc: "Atop a tower after defeating Commander Niall", replaces: "Haligtree Secret Medallion (Left)", cat: "key" },
      { desc: "Dropped by Commander Niall in Castle Sol", replaces: "Veteran's Prosthesis", cat: "major" },
      { desc: "Dropped by Borealis the Freezing Fog", replaces: "Dragon Heart", cat: "boss" },
      { desc: "Dropped by Roundtable Knight Vyke in the Lord Contender's Evergaol", replaces: "Fingerprint Helm, Fingerprint Armor, Fingerprint Gauntlets, Fingerprint Greaves, Vyke's Dragonbolt", cat: "boss" },
      { desc: "Dropped by self-cloning Erdtree Avatars", replaces: "Cerulean Crystal Tear (Alternate), Crimson Bubbletear", cat: "boss" },
      { desc: "Dropped by the Death Rite Bird on the way from Snow Valley Ruins Overlook to Castle Sol", replaces: "Death Ritual Spear", cat: "boss" },
      { desc: "At a statue in the First Church of Marika at the southmost end of Freezing Lake", replaces: "Sacred Tear", cat: "flask" },
      { desc: "Under a Golden Seed tree overlooking a chasm along the right wall of the ascent from Ancient Snow Value Ruins, straight south from the Freezing Lake Site of Grace", replaces: "Golden Seed", cat: "flask" },
      { desc: "Sold by the Hermit Merchant along a cliffside to the west of Stargazer's Ruins", replaces: null, cat: "shop" },
      { desc: "Spiritcaller Cave - Dropped by Spiritcaller Snail (Godskin Summoner)", replaces: "Godskin Swaddling Cloth, Black Flame Ritual", cat: "boss" },
    ]},
    { name: "Flame Peak", items: [
      { desc: "Dropped by Fire Giant", replaces: "Remembrance of the Fire Giant", cat: "major" },
      { desc: "At the statue in Church of Repose, in southwest Flame Peak", replaces: "Sacred Tear", cat: "flask" },
      { desc: "North of Foot of the Forge Site of Grace", replaces: "Golden Seed", cat: "flask" },
      { desc: "Giant-Conquering Hero's Grave - Dropped by Ancient Hero of Zamor", replaces: "Zamor Curved Sword, Zamor Mask, Zamor Armor, Zamor Bracelets, Zamor Legwraps", cat: "boss" },
      { desc: "Giants' Mountaintop Catacombs - Dropped by Ulcerated Tree Spirit", replaces: "Glovewort Picker's Bell Bearing [2], Golden Seed", cat: "boss" },
    ]},
    { name: "Farum Azula", items: [
      { desc: "Dropped by Godskin Duo", replaces: "Smithing-Stone Miner's Bell Bearing [4], Ash of War: Black Flame Tornado", cat: "major" },
      { desc: "Dropped by Dragonlord Placidusax", replaces: "Remembrance of the Dragonlord", cat: "major" },
      { desc: "Dropped by Maliketh, the Black Blade", replaces: "Remembrance of the Black Blade", cat: "major" },
      { desc: "After using a Stonesword Key and ascending Dragon Temple Lift, past a plaza fountain", replaces: "Golden Seed", cat: "flask" },
      { desc: "Under a Golden Seed tree guarded by four eagles. From Dragon Temple Rooftop, descend to the platform with the low-health AOE-spamming dragon, and double back along the left edge until you see a thatched red rooftop. Jump the gap to it and jump up again to find the tree", replaces: "Golden Seed", cat: "flask" },
    ]},
    { name: "Chapel of Anticipation", items: [
      { desc: "Dropped by Grafted Scion", replaces: "Ornamental Straight Sword, Golden Beast Crest Shield", cat: "boss" },
    ]},
    { name: "Hidden Path to the Haligtree", items: [
      { desc: "Dropped by Stray Mimic Tear", replaces: "Blackflame Monk Amon", cat: "boss" },
    ]},
    { name: "Consecrated Snowfield", items: [
      { desc: "Dropped by a Death Rite Bird at the north end of the frozen-over river, between Ordina and Apostate Derelict. They only spawn at night", replaces: "Explosive Ghostflame", cat: "boss" },
      { desc: "Dropped by Great Wyrm Theodrix at the base of the frozen waterfall, east of the Inner Consecrated Snowfield Site of Grace", replaces: "Dragon Heart 3x", cat: "boss" },
      { desc: "Dropped by the Night's Cavalry Duo tagging alongside the Caravan southwest of Inner Consecrated Snowfield Site of Grace. They only spawn at night", replaces: "Ancient Dragon Smithing Stone, Night's Cavalry Helm, Night's Cavalry Armor, Night's Cavalry Gauntlets, Night's Cavalry Greaves", cat: "boss" },
      { desc: "Dropped by the Putrid Avatar at the Consecrated Snowfield Minor Erdtree", replaces: "Thorny Cracked Tear, Ruptured Crystal Tear (Alternate)", cat: "boss" },
      { desc: "Under a Golden Seed tree in Ordina, Liturgical Town", replaces: "Golden Seed", cat: "flask" },
      { desc: "Under a Golden Seed tree in the foggy area northeast of the Consecrated Snowfield Site of Grace", replaces: "Golden Seed", cat: "flask" },
      { desc: "Consecrated Snowfield Catacombs - Dropped by Putrid Grave Warden Duelist", replaces: "Rotten Gravekeeper Cloak, Great Grave Glovewort 2x", cat: "boss" },
      { desc: "Cave of the Forlorn - Dropped by Misbegotten Crusader", replaces: "Golden Order Greatsword", cat: "boss" },
      { desc: "Yelough Anix Tunnel - Dropped by Astel, Stars of Darkness", replaces: "Meteorite of Astel", cat: "boss" },
    ]},
    { name: "Haligtree", items: [
      { desc: "Dropped by Loretta, Knight of the Haligtree", replaces: "Loretta's War Sickle, Loretta's Mastery", cat: "major" },
      { desc: "Dropped by Malenia", replaces: "Malenia's Great Rune, Remembrance of the Rot Goddess", cat: "major" },
    ]},
    { name: "Mohgwyn", items: [
      { desc: "Dropped by Mohg, Lord of Blood", replaces: "Mohg's Great Rune, Remembrance of the Blood Lord", cat: "major" },
      { desc: "Under a Golden Seed tree in the lake of blood, visible from the first Site of Grace", replaces: "Golden Seed", cat: "flask" },
      { desc: "Sold by the Imprisoned Merchant in the cave with Sanguine Nobles before Dynasty Mausoleum Midpoint", replaces: null, cat: "shop" },
    ]},
    { name: "Ashen Leyndell", items: [
      { desc: "Dropped by Hoarah Loux", replaces: "Remembrance of Hoarah Loux", cat: "major" },
      { desc: "Dropped by Gideon", replaces: "Scepter of the All-Knowing, All-Knowing Helm, All-Knowing Armor, All-Knowing Gauntlets, All-Knowing Greaves", cat: "boss" },
    ]},
    { name: "Stone Platform", items: [
      { desc: "Dropped by Elden Beast", replaces: "Elden Remembrance", cat: "major" },
    ]},
  ]},
  { section: "Shadow of the Erdtree", locations: [
    { name: "Gravesite Plain", items: [
      { desc: "Dropped by Blackgaol Knight in the Western Nameless Mausoleum", replaces: "Greatsword of Solitude, Helm of Solitude, Armor of Solitude, Gauntlets of Solitude, Greaves of Solitude", cat: "boss" },
      { desc: "Dropped by Ghostflame Dragon", replaces: "Dragon Heart, Somber Ancient Dragon Smithing Stone", cat: "boss" },
      { desc: "Sold by Moore", replaces: null, cat: "shop" },
      { desc: "By Miquella's Cross at Main Gate Cross", replaces: "Scadutree Fragment", cat: "blessing" },
      { desc: "By Miquella's Cross at the Pillar Path Cross grace", replaces: "Scadutree Fragment", cat: "blessing" },
      { desc: "By Miquella's Cross at the Three-Path Cross", replaces: "Scadutree Fragment", cat: "blessing" },
      { desc: "In front of a beheaded Marika statue in the Castle Front enemy camp", replaces: "Scadutree Fragment", cat: "blessing" },
      { desc: "In front of the beheaded Marika statue in the Church of Consolation", replaces: "Scadutree Fragment 2x", cat: "blessing" },
      { desc: "On a large withered corpse by the lake northeast of Prospect Town, along the cliff's edge", replaces: "Revered Spirit Ash", cat: "blessing" },
      { desc: "On a large withered corpse on the cliffside east of Scorched Ruins overlooking Church of Consolation below", replaces: "Revered Spirit Ash", cat: "blessing" },
      { desc: "On a large withered corpse on the east cliffside of Abandoned Ailing Village, east of the hill containing the rest of the village", replaces: "Revered Spirit Ash", cat: "blessing" },
      { desc: "Fog Rift Catacombs - Dropped by Death Knight", replaces: "Death Knight's Twin Axes, Crimson Amber Medallion +3", cat: "boss" },
      { desc: "Belurat Gaol - Dropped by Demi-Human Swordmaster Onze", replaces: "Demi-Human Swordsman Yosh", cat: "boss" },
      { desc: "Dragon's Pit - Dropped by Ancient Dragon-Man", replaces: "Dragon-Hunter's Great Katana", cat: "boss" },
    ]},
    { name: "Belurat", items: [
      { desc: "On a corpse accessible from the bridge above the crest of the dirty waterfall, accessed by climbing up the ladder to the west, looping counterclockwise around the outside of the building, jumping to the bridge, and entering the room to the east", replaces: "Well Depths Key", cat: "key" },
      { desc: "Dropped by Divine Beast Dancing Lion", replaces: "Remembrance of the Dancing Lion", cat: "major" },
      { desc: "By the Miquella's Cross hidden in Belurat, accessed through a doorway found by climbing over rubble to the right of the scorpion tower entrance", replaces: "Scadutree Fragment", cat: "blessing" },
      { desc: "On a large withered corpse facing the large tree on the way to Stagefront", replaces: "Revered Spirit Ash", cat: "blessing" },
      { desc: "On the large withered statue in the scorpion room before the Tower Settlement grace", replaces: "Revered Spirit Ash 2x", cat: "blessing" },
      { desc: "On a large withered corpse up the elevator from the Theatre of the Divine Beast", replaces: "Revered Spirit Ash", cat: "blessing" },
    ]},
    { name: "Ellac River", items: [
      { desc: "On a large withered corpse in the cave section north of the Ellac River Cave grace", replaces: "Revered Spirit Ash", cat: "blessing" },
      { desc: "Rivermouth Cave - Dropped by Chief Bloodfiend in Rivermouth Cave", replaces: "Bloodfiend Hexer's Ashes", cat: "boss" },
    ]},
    { name: "Cerulean Coast", items: [
      { desc: "Dropped by Dancer of Ranah in the Southern Nameless Mausoleum", replaces: "Dancing Blade of Ranah, Dancer's Hood, Dancer's Dress, Dancer's Bracer, Dancer's Trousers", cat: "boss" },
      { desc: "Dropped by Demi-Human Queen Marigga on the beach past the ravine northeast of the Cerulean Coast West grace", replaces: "Star-Lined Sword", cat: "boss" },
      { desc: "Dropped by the Ghostflame Dragon south of the Cerulean Coast grace", replaces: "Dragon Heart, Somber Ancient Dragon Smithing Stone", cat: "boss" },
      { desc: "By Miquella's Cross at the Cerulean Coast Cross grace", replaces: "Scadutree Fragment", cat: "blessing" },
      { desc: "On a corpse guarded by an enemy in a small cave along the ravine from Cerulean Coast West to the far west beach, through an entrance in the north cliff as you head west after making  two lefts", replaces: "Scadutree Fragment", cat: "blessing" },
    ]},
    { name: "Fog Rift Fort", items: [
      { desc: "Dropped by Black Knight Garrew in the east building of Fog Rift Fort", replaces: "Black Steel Greatshield", cat: "boss" },
    ]},
    { name: "Castle Ensis", items: [
      { desc: "In a chest in the tower on the castle's southeast rampart, before the elevator up to Castle-Lord's Chamber", replaces: "Imbued Sword Key", cat: "key" },
      { desc: "Dropped by Rellana, Twin Moon Knight", replaces: "Remembrance of the Twin Moon Knight", cat: "major" },
      { desc: "By Miquella's Cross at the Castle Ensis Checkpoint grace", replaces: "Scadutree Fragment", cat: "blessing" },
    ]},
    { name: "Scadu Altus", items: [
      { desc: "Given by Count Ymir when you first meet him in Manus Metyr", replaces: "Hole-Laden Necklace, Ruins Map", cat: "key" },
      { desc: "In front of the tree to the north of Bonny Village, along the cliffbottom east of Moorth Ruins", replaces: "O Mother", cat: "key" },
      { desc: "Dropped by Black Knight Edredd in Fort of Reprimand", replaces: "Ash of War: Aspects of the Crucible: Wings", cat: "boss" },
      { desc: "Dropped by Ralva the Great Red Bear", replaces: "Pelt of Ralva", cat: "boss" },
      { desc: "Dropped by the Ghostflame Dragon fighting enemies on Moorth Highway", replaces: "Dragon Heart, Somber Ancient Dragon Smithing Stone", cat: "boss" },
      { desc: "By Miquella's Cross at the Highroad Cross grace", replaces: "Scadutree Fragment", cat: "blessing" },
      { desc: "By Miquella's Cross at the Moorth Ruins grace", replaces: "Scadutree Fragment", cat: "blessing" },
      { desc: "In front of a beheaded Marika statue in the enemy camp west of Moorth Ruins", replaces: "Scadutree Fragment", cat: "blessing" },
      { desc: "In front of the beheaded Marika statue in the large enemy camp south of Shadow Keep", replaces: "Scadutree Fragment", cat: "blessing" },
      { desc: "In front of the beheaded Marika statue north of the small lake north of Moorth Ruins", replaces: "Scadutree Fragment", cat: "blessing" },
      { desc: "On a corpse in front of the headless Marika statue in the Church of the Crusade", replaces: "Scadutree Fragment 2x", cat: "blessing" },
      { desc: "On a large withered corpse at the far north end of the gully between the east and west halves of Bonny Village", replaces: "Revered Spirit Ash", cat: "blessing" },
      { desc: "On the large withered corpse along the cliffside east of Moorth Ruins", replaces: "Revered Spirit Ash", cat: "blessing" },
      { desc: "By Miquella's Cross at the Scaduview Cross grace, accessible from the sealed spiritspring below", replaces: "Scadutree Fragment", cat: "blessing" },
      { desc: "Darklight Catacombs - Dropped by Jori, Elder Inquisitor", replaces: "Barbed Staff-Spear", cat: "boss" },
      { desc: "Bonny Gaol - Dropped by Curseblade Meera", replaces: "Curseblade Meera", cat: "boss" },
    ]},
    { name: "Lower Scadu Altus", items: [
      { desc: "Dropped by Rakshasa in the Eastern Nameless Mausoleum", replaces: "Rakshasa's Great Katana, Rakshasa Helm, Rakshasa Armor, Rakshasa Gauntlets, Rakshasa Greaves", cat: "boss" },
      { desc: "At the bottom of the waterfall below the Recluses' River Upstream grace, accessed by heading northeast from the Recluses' River Downstream grace and dropping down (but not too far) and heading north", replaces: "Scadutree Fragment", cat: "blessing" },
      { desc: "On a large withered corpse west of the upper Village of Flies area", replaces: "Revered Spirit Ash", cat: "blessing" },
      { desc: "On the large withered corpse in southeast Castle Watering Hole", replaces: "Revered Spirit Ash", cat: "blessing" },
    ]},
    { name: "Shadow Keep", items: [
      { desc: "Dropped by Golden Hippopotamus", replaces: "Aspects of the Crucible: Thorns, Scadutree Fragment 2x", cat: "major" },
    ]},
    { name: "Shadow Keep - Church District", items: [
      { desc: "On the left hand of the giant Marika statue in the cathedral, accessible from the second floor. For utmost safety, drain the water first", replaces: "Scadutree Fragment", cat: "blessing" },
    ]},
    { name: "Specimen Storehouse", items: [
      { desc: "Dropped by Messmer the Impaler", replaces: "Remembrance of the Impaler, Messmer's Kindling", cat: "major" },
      { desc: "By Miquella's Cross at the Storehouse Fourth Floor grace", replaces: "Scadutree Fragment", cat: "blessing" },
      { desc: "In front of a beheaded Marika statue right before the Dark Chamber Entrance", replaces: "Scadutree Fragment", cat: "blessing" },
      { desc: "On top of a hanging beast which can be jumped to from a balcony on the seventh floor", replaces: "Revered Spirit Ash", cat: "blessing" },
      { desc: "On top of the beast in front of the first floor grace, accessed by jumping from the wooden table in front of the grace", replaces: "Revered Spirit Ash", cat: "blessing" },
    ]},
    { name: "Scadutree Base", items: [
      { desc: "Dropped by Scadutree Avatar", replaces: "Remembrance of the Shadow Sunflower, Miquella's Great Rune", cat: "major" },
    ]},
    { name: "Stone Coffin Fissure", items: [
      { desc: "Dropped by Putrescent Knight", replaces: "Remembrance of Putrescence", cat: "major" },
      { desc: "By Miquella's Cross at the Fissure Cross grace", replaces: "Scadutree Fragment", cat: "blessing" },
    ]},
    { name: "Rauh Base", items: [
      { desc: "Dropped by Rugalea the Great Red Bear", replaces: "Roar of Rugalea", cat: "boss" },
      { desc: "Dropped by Red Bear in the Northern Nameless Mausoleum", replaces: "Red Bear's Claw, Iron Rivet Armor, Iron Rivet Gauntlets, Iron Rivet Greaves, Fang Helm", cat: "boss" },
      { desc: "On a corpse on a walkway overlooking the blocked off building in Temple Town Ruins, accessed by entering through a broken wall to the south, then when climbing along the north wall of the building to access the upper level, jumping over to the left instead of dropping down", replaces: "Scadutree Fragment", cat: "blessing" },
      { desc: "Scorpion River Catacombs - Dropped by Death Knight", replaces: "Death Knight's Longhaft Axe, Cerulean Amber Medallion +3", cat: "boss" },
    ]},
    { name: "Ancient Ruins of Rauh", items: [
      { desc: "Dropped by Romina, Saint of the Bud", replaces: "Remembrance of the Saint of the Bud", cat: "major" },
      { desc: "Dropped by Divine Beast Dancing Lion at the bottom of the Grand Stairway", replaces: "Divine Beast Tornado", cat: "boss" },
      { desc: "By Miquella's Cross at the East Ruins grace", replaces: "Scadutree Fragment", cat: "blessing" },
      { desc: "In front of the northwest wall monument on the second floor of the cave after the West Ruins grace", replaces: "Scadutree Fragment", cat: "blessing" },
      { desc: "On a large withered corpse in the gazebo in the West Ruins second-story courtyard", replaces: "Revered Spirit Ash", cat: "blessing" },
    ]},
    { name: "Scaduview", items: [
      { desc: "Dropped by Commander Gaius", replaces: "Remembrance of the Wild Boar Rider", cat: "major" },
      { desc: "In front of the beheaded Marika statue east of Shadow Keep Back Gate", replaces: "Scadutree Fragment", cat: "blessing" },
      { desc: "In front of the Scadutree Chalice", replaces: "Scadutree Fragment, Scadutree Fragment, Scadutree Fragment, Scadutree Fragment, Scadutree Fragment", cat: "blessing" },
    ]},
    { name: "Abyssal Woods", items: [
      { desc: "In front of the statue pedestal in Abandoned Church", replaces: "Scadutree Fragment 2x", cat: "blessing" },
      { desc: "On a corpse in front of a tree in the ravine north of the Abyssal Woods grace, by the west edge", replaces: "Scadutree Fragment", cat: "blessing" },
    ]},
    { name: "Midra's Manse", items: [
      { desc: "Dropped by Midra, Lord of Frenzied Flame", replaces: "Remembrance of the Lord of Frenzied Flame", cat: "major" },
      { desc: "On a corpse on a chandelier, accessed by jumping to the north from the Second Floor Chamber grace", replaces: "Revered Spirit Ash", cat: "blessing" },
    ]},
    { name: "Jagged Peak", items: [
      { desc: "Dropped by Bayle the Dread", replaces: "Heart of Bayle", cat: "major" },
      { desc: "Dropped by Ancient Dragon Senessax", replaces: "Ancient Dragon Smithing Stone, Somber Ancient Dragon Smithing Stone", cat: "boss" },
      { desc: "On a corpse under where the boulder starts rolling climbing the hill before Senessax's lake", replaces: "Scadutree Fragment", cat: "blessing" },
    ]},
    { name: "Foot of the Jagged Peak", items: [
      { desc: "Dropped by Jagged Peak Drake in the lake east of Dragon's Pit Terminus", replaces: "Dragon Heart, Dragonscale Flesh", cat: "boss" },
      { desc: "Dropped by the Jagged Peak Drake fighting another drake where Igon spectates", replaces: "Dragon Heart, Dragonscale Flesh", cat: "boss" },
    ]},
    { name: "Charo's Hidden Grave", items: [
      { desc: "Dropped by Death Rite Bird in the gravebird lake", replaces: "Ash of War: Ghostflame Call", cat: "boss" },
      { desc: "Lamenter's Gaol - Dropped by Lamenter", replaces: "Lamenter's Mask", cat: "boss" },
    ]},
    { name: "Hinterland", items: [
      { desc: "Dropped by Fallingstar Beast in the crater northeast of the Fingerstone Hill grace", replaces: "Gravitational Missile", cat: "boss" },
      { desc: "Dropped by the first Tree Sentinel in Hinterland", replaces: "Blessing of Marika", cat: "boss" },
      { desc: "Dropped by the second Tree Sentinel in Hinterland", replaces: "Blessing of Marika", cat: "boss" },
    ]},
    { name: "Finger Birthing Grounds", items: [
      { desc: "Dropped by Metyr, Mother of Fingers", replaces: "Remembrance of the Mother of Fingers", cat: "major" },
      { desc: "Dropped by Count Ymir after he invades in Manus Metyr after defeating Metyr", replaces: "Maternal Staff, High Priest Hat, High Priest Robe, High Priest Gloves, High Priest Undergarments, Ymir's Bell Bearing", cat: "boss" },
    ]},
    { name: "Enir-Ilim", items: [
      { desc: "Dropped by Promised Consort Radahn", replaces: "Remembrance of a God and a Lord", cat: "major" },
      { desc: "By Miquella's Cross at the Spiral Rise grace", replaces: "Scadutree Fragment", cat: "blessing" },
      { desc: "In front of an altar in the top room of a side tower after the Spiral Rise grace, shortly before reentering the rise from higher up. It's up the stairs from the rooftop section with gravebirds, before the second shorter rooftop section", replaces: "Scadutree Fragment", cat: "blessing" },
      { desc: "In front of the altar in the Cleansing Chamber Anteroom", replaces: "Scadutree Fragment", cat: "blessing" },
      { desc: "On a large withered corpse in a shrine after the rooftop section with gravebirds after the Spiral Rise grace, entering a doorway to the left instead of up the stairs to the right", replaces: "Revered Spirit Ash", cat: "blessing" },
      { desc: "On a large withered corpse in front of several man-flies, accessed by ascending the stairs southwest of the First Rise grace, falling down the broken bridge, and entering the room to the northwest", replaces: "Revered Spirit Ash 2x", cat: "blessing" },
      { desc: "In front of a statue along the dropdown to Euporia in Belurat, after reentering Belurat. From the area with a spiral column gazebo before the final flight of stairs up to Spiral Rise, descend the stairs northeast of the gazebo, jump down to the stairs to the southeast, and continue dropping down until a final jump to a windowsill below. The statue is on the left after exiting the room", replaces: "Scadutree Fragment", cat: "blessing" },
    ]},
  ]},
];
